문제1. 다음과 같은 2차원 배열을 생성하고 array_2d에서 선언하는 파이썬 코드를 작성하시오.

[[1, 2, 3], <br>
&nbsp; [4, 5, 6], <br>
&nbsp; [7, 8, 9]]

In [22]:
import numpy as np

In [23]:
array_2d = np.array([
            [1, 2, 3],
            [4, 5, 6],
            [7, 8, 9]
])
print(array_2d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [25]:
array = np.arange(1, 10).reshape(3, 3)
print(array)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


문제2. 모든 값이 1(정수)이고 3층 2행 4열인 3차원 배열을 만드시오.

In [27]:
arr_3d = np.ones([3, 2, 4], dtype="int")
print(arr_3d)

[[[1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]]]


문제3. array_2d의 2차원 배열에서 2열의 요소만 나열하시오. 


[[1, 2, 3], <br>
&nbsp; [4, 5, 6], <br>
&nbsp; [7, 8, 9]]

In [30]:
print(array_2d[0:3, 1])

[2 5 8]


문제4. arr_a 는 arange()를 이용하여 2행 2열의 배열을 생성하고, 각각의 요소에 5를 더하시오 

In [32]:
arr_a = np.arange(4).reshape(2,2)
print(arr_a + 5)

[[5 6]
 [7 8]]


문제5. 다음과 같은 1차원 배열 a와 2차원 배열 b가 있습니다. 각각의 요소를 곱하는 코드를 만드시오 

* a = [1, 2, 3]
* b = [[10, 20, 30], [40, 50, 60], [70, 80, 90]]

In [40]:
a = [1, 2, 3]
b = [[10, 20, 30], [40, 50, 60], [70, 80, 90]]

arr_1d = np.array(a)
arr_2d = np.array(b)
arr_1d * arr_2d

print(arr_1d)
print(arr_2d)
print(arr_1d * arr_2d)
np.multiply(arr_1d, arr_2d)

[1 2 3]
[[10 20 30]
 [40 50 60]
 [70 80 90]]
[[ 10  40  90]
 [ 40 100 180]
 [ 70 160 270]]


array([[ 10,  40,  90],
       [ 40, 100, 180],
       [ 70, 160, 270]])

문제6. c = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9] 를 5행 2열로 변경하는 코드를 작성하시오

In [42]:
c = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

array = np.array(c).reshape(5, 2)
print(array)

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
