In [4]:
a = [
    [1, 2, 3], 
    [4, 5, 6]]

a[0] #첫 번째 열
a[1] #두 번째 열
a[1][2] #두 번째 열, 마지막 숫자인 6

a * 2


[[1, 2, 3], [4, 5, 6], [1, 2, 3], [4, 5, 6]]

In [6]:
# NumPy 설치
!pip install numpy

     ---------------------------------------- 0.0/59.7 kB ? eta -:--:--
     ------ --------------------------------- 10.2/59.7 kB ? eta -:--:--
     ------------- ------------------------ 20.5/59.7 kB 217.9 kB/s eta 0:00:01
     ------------------- ------------------ 30.7/59.7 kB 217.9 kB/s eta 0:00:01
     -------------------------------- ----- 51.2/59.7 kB 292.6 kB/s eta 0:00:01
     -------------------------------------- 59.7/59.7 kB 317.3 kB/s eta 0:00:00
   ---------------------------------------- 0.0/12.6 MB ? eta -:--:--
   ---------------------------------------- 0.1/12.6 MB 6.4 MB/s eta 0:00:02
   - -------------------------------------- 0.5/12.6 MB 7.1 MB/s eta 0:00:02
   -- ------------------------------------- 0.9/12.6 MB 8.2 MB/s eta 0:00:02
   ---- ----------------------------------- 1.5/12.6 MB 9.8 MB/s eta 0:00:02
   ------- -------------------------------- 2.4/12.6 MB 11.8 MB/s eta 0:00:01
   ----------- ---------------------------- 3.5/12.6 MB 14.1 MB/s eta 0:00:01
 


[notice] A new release of pip is available: 24.0 -> 24.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [8]:
import numpy

a = [1, 2, 3, 4, 5, 6]
numpy.array(a)
print("a: ", a)
print(type(a))
b = numpy.array(a)
print("b: ", b)
print(type(b))

a:  [1, 2, 3, 4, 5, 6]
<class 'list'>
b:  [1 2 3 4 5 6]
<class 'numpy.ndarray'>


In [9]:
import numpy as np

np.array([1, 3, 5, 7, 9])

array([1, 3, 5, 7, 9])

In [10]:
np.array("d a t a e d u")


array('d a t a e d u', dtype='<U13')

In [11]:
np.arange(7) #range(7)과 동일, numpy의 range임.


array([0, 1, 2, 3, 4, 5, 6])

In [14]:
np.arange(1, 6, 0.5)

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5])

In [16]:
# 파이썬 내장함수 range()
list(range(1, 6, 2))

[1, 3, 5]

In [17]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [19]:
np.ones([2, 2])
# 2행 2열의 shape를 만들겠다

array([[1., 1.],
       [1., 1.]])

In [20]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [21]:
np.zeros([3, 2])

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [22]:
np.full(5, 3)
#5개가 들어갈껀데 3으로 만들겠다

array([3, 3, 3, 3, 3])

In [25]:
np.full(5, 4).dtype
# 각각의 요소는 정수로 이루어져 있다

dtype('int64')

In [28]:
np.full(5, 4.).dtype
# 각각의 요소는 실수로 이루어져 있다

dtype('float64')

In [30]:
np.full(5, 4, dtype="float").dtype
# dtype라는 인수를 실수로 지정해줌

dtype('float64')

In [31]:
# 2차원 배열

#2행 5열
np.array([
    [1, 3, 5, 7, 9],
    [2, 4, 6, 8 ,10]
])

array([[ 1,  3,  5,  7,  9],
       [ 2,  4,  6,  8, 10]])

In [32]:
#3행 3열
np.array([
    [1, 2, 3], 
    [4, 5, 6],
    [7, 8, 9]
])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [35]:
np.ones((2, 5), dtype="int")

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [36]:
np.zeros((2, 5), dtype="int")

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [37]:
np.full((2, 5), 5)

array([[5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5]])